name = "lucia-hono-d1"
main = "src/index.ts"
compatibility_date = "2024-03-01"

[[d1_databases]]
binding = "DB"
database_name = "my-database"
database_id = "_"
preview_database_id = "local"
migrations_dir = "./migrations"